apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  releaseName: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: 21.1.1
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
